#!/bin/bash
#===============================================
# Functions run in the background by pipe()
#===============================================

###########  Commands functions  ############
# Edit this part to customize the actions run
#  in the background by the commands
# The pipe run :
#  _background_init "{$args[@]}"
#  _background_<command name> "{$args[@]}"
# Where "{$args[@]}" is a list of papis folders
# build-indexes is a command

_background_edit (){
   _update_database "${dflist[@]}"
   build-indexes --quiet "${flist[@]}"
}

_background_delete (){
   papis rm -f -a "${dflist[@]}" 2>>$tmplog

   _background_notification "The following entries has been deleted :"
   build-indexes --quiet "${flist[@]}"
}

_background_add (){
   # Set add-fetch-citations = True in papis config to build automatically a citations file

   # Compare the library before and after the adding of the new entry
   # To grab the new folder created
   tmpbefore=$tmpdir/add-folders-before
   tmpafter=$tmpdir/add-folders-after
   find '/home/archx/Documents/papers' -mindepth 1 -type d > $tmpbefore

   # Papis command
   eval "papis add --batch $@ &>>$tmplog"

   find '/home/archx/Documents/papers' -mindepth 1 -type d > $tmpafter
   iscreated=$(diff $tmpbefore $tmpafter | tail -1)

   if [[ -n $iscreated ]]; then
      flabels="$(_set_flabels ${iscreated:2})"
      build-indexes --quiet "${iscreated:2}"
      _background_notification "A new entry has been added to the papis library"
   else
      _background_notification "No entry has been added to the library" "See $tmplog for details."
   fi
}

_background_tag (){
   _update_database "${dflist[@]}"
   build-indexes --quiet "${flist[@]}"
}

_background_browse (){
   papis browse -a "${dflist[@]}" 2>> $tmplog
}

################################
#######  core functions  #######
# Do not edit this part
# These functions are used by the functions above

# Update papis database
_update_database (){
   papis update -b "$@" 2>>$tmplog
}

# Display notifications
_background_notification (){
   if [[ $enable_notifications == 1 ]]; then
      $notifyscript "$@" "$flabels" 2> /dev/null
   fi
}

# Set
#  1) flist: a list of papis-folders to send to build-indexes
#  2) dflist: list of '--doc-folder' 'papis-folder' to send to papis
#  3) flabels: a list of 'labels' (for notifications)
#   from the folders list given to _pipe
_background_init (){
   flist=()
   dflist=()
   flabels=""
   for folder in "$@"; do
      dflist+=("--doc-folder")
      dflist+=("$folder")
      flist+=("$folder")
      flabels+="$(_set_flabels $folder)"
   done
}

# The 'label' is the 1st 40 characters of the entry title
_set_flabels (){
   yml="$1/info.yaml"
   if [[ -f $yml ]]; then
      title=$(grep "^title:" "$yml" 2>/dev/null)
      title="${title#*: }"
      [[ -n $title ]] && echo "${title:0:40}\n"
   fi
}
