#!/bin/bash

# Open a pipe to run processes on the background
# There is one pipe for each papis-fzf instance
# $1 pipe name ; $2 pid papis-fzf
# To use the pipe, just `echo <text> > $pipe`
# The <text> must be formatted as follow:
#  first line: the command to run
#  second line: the notification text to display after (can be empty)
#  third+ lines: the papis folders, one folder by line

_pipe (){
   [[ ! -p $1 ]] && mkfifo "$1"
   while [[ -p $1 ]]; do
      if read -r pipein < "$1"; then
         [[ $pipein == "exit" ]] && exit

         # Set the function to run and the arguments
         func=$(echo -e "$pipein" | head -1)
         args=()
         while read line; do
            [[ -n $line ]] && args+=("$line")
         done < <(echo -e "$pipein" | tail -n +2)

         # Run the function
         [[ -n ${args[@]} ]] && _background_init "${args[@]}"
         $func "${args[@]}"

         # Debug log
         if [[ $debug == 1 ]]; then
            echo "papis-fzf DEBUG :: pipe - function : $func" >> $tmplog
            echo "papis-fzf DEBUG :: pipe - arg :" >> $tmplog
            echo -e "$args" >> $tmplog
         fi

         # Refresh the fzf menus of all papis-fzf instances opened
         sleep .3
         fzfpids=$(pgrep fzf-papis)
         [[ -n $fzfpids ]] && kill $fzfpids

      fi
   done
}
