#!/bin/bash
#===============================================
# Browse entries
# Use papis browse
#===============================================
browse (){
   [[ -z $@ ]] && return
 # Exit and send urls to the navigator in the background
   pipeinput="_background_browse\n"
   pipeinput+="$(printf '%s\\n' $@)"
   echo "$pipeinput" > $pipe

 # Exit or hide if HIDE_ON_EXIT
   if [[ -n $HIDE_ON_EXIT ]]; then
      termpid=$(pgrep -P $HIDE_ON_EXIT)
      window=$(xdo id -p $termpid)
      $hidescript $window
   else
      exit
   fi
}
