#!/bin/bash
#===============================================
# Internal command run by the fzf --preview flag
# preview_help is set by papis-fzf
#===============================================
preview (){
   [[ -f $preview_help ]] && help=$(< $preview_help)
   [[ -n $help ]] && echo -n "" > $preview_help

   # Run the help script setting the help message texts
   if [[ -n $help ]]; then
      $helpscript $help
   # If there is nothing to display, exit
   elif [[ -z $@ ]]; then
      exit

   # Preview in cite fzf menu
   elif [[ $1 == "cite" ]]; then
      shift
      line="$@"
      line="${line% $cite_separator *}"
      line="$line $cite_separator"
      nxtline=$(grep -A 1 "$line" $cite_file | tail -1)
      [[ ${nxtline:0:1} == "#" ]] && nxtline="${nxtline:1}"

      if [[ $cite_preview_color =~ ^[0-9]+$ ]]; then
         nxtline="\033[${cite_preview_color}m${nxtline}"
         nxtline="${nxtline//[0m/[0m\\033[${cite_preview_color}m}"
      fi

      echo -e "${nxtline}"

   # Preview in citations fzf menu
   elif [[ $1 == "citations" ]]; then
      shift

      # Files
      cttraw=$tmpdir/tmp-index-citations-raw
      cttcolor=$tmpdir/tmp-index-citations-colored
      cttiraw=$tmpdir/tmp-index-citations-info-raw
      ctticolor=$tmpdir/tmp-index-citations-info-colored

      # Try to determine which line to display from which file
      where=$(grep -n "$1" $cttraw $cttiraw | head -1)

      if [[ ${where%%:*} == $cttraw ]]; then
         n=${where#*:}
         n=${n%%:*}
         line=$(sed "${n}q;d" $cttcolor)
      else
         n=${where#*:}
         n=${n%%:*}
         line=$(sed "${n}q;d" $ctticolor)
      fi

      # Echo the text to show
      echo -e "$line" | fold -w 95 -s

   # Preview in all the others fzf menus
   else
      # Get the index nth
      line=$(sed 's/ *$//' <<< $@)
      n=$(grep -n "$line" $indexraw)
      n="${n%%:*}"

      # Get the colored line
      text=$(sed "${n}q;d" $indexcolored)

      # My "note:" field start with the color code 93m
      # I want it to be displayed on a new line
      text="${text/93m/93m\\n}"

      # Echo the text
      echo -e "$text" | fold -w 95 -s
   fi
}
