#!/bin/bash
# This script set the fzf environnement

_fzf_env (){
   if [[ $1 == "main" ]]; then
    # Default env (listAll/listAdvanced)
      # In main menu, you can run a command querying :command in fzf
      # The key bindings echo the same command starting by :
      export FZF_DEFAULT_OPTS="--reverse -m --ansi --print-query --no-clear\
                               --bind 'change:first' \
                               --bind 'enter:execute(echo "!:cite")+accept' \
                               --bind '$main_searchbytags:execute(echo "!:search-by-tags")+accept' \
                               --bind '$main_show:execute(echo "!:show")+accept' \
                               --bind '$main_edit:execute(echo "!:edit")+accept' \
                               --bind '$main_delete:execute(echo "!:delete")+accept' \
                               --bind '$main_browse:execute(echo "!:browse")+accept' \
                               --bind '$main_tag:execute(echo "!:tag")+accept' \
                               --bind '$main_citations:execute(echo "!:citations")+accept' \
                               --bind '$main_export:execute(echo "!:xport")+accept' \
                               --bind '$main_refresh:execute(echo "!:refresh")+abort' \
                               --bind '$main_yank:execute-silent($yankscript {})' \
                               --bind '$selectall:select-all' \
                               --bind '$deselectall:deselect-all' \
                               --bind 'esc:execute(echo "!:exit")+abort' \
                               --bind '$help:execute-silent(echo "main" > $preview_help)+refresh-preview' \
                               --preview='papis-fzf preview {}' \
                               --preview-window='bottom,30%,wrap'"
   elif [[ $1 == "search-by-tags" ]]; then
    # Used by search-by-tags
      export FZF_DEFAULT_OPTS="--reverse -m --print-query --no-clear \
                               --bind 'change:first' \
                               --bind '$tags_or:execute(echo "!or")+accept' \
                               --bind '$selectall:select-all' \
                               --bind '$deselectall:deselect-all' \
                               --bind '$help:execute-silent(echo "searchbytags" > $preview_help)+refresh-preview' \
                               --preview='papis-fzf preview' \
                               --preview-window='bottom,8%,wrap,border-none'"
   elif [[ $1 == "tag" ]]; then
    # Used by tag
      export FZF_DEFAULT_OPTS="--reverse -m --print-query --no-clear \
                               --bind 'change:first' \
                               --bind '$tag_query_and_add:execute(echo "!queryaddtag")+accept' \
                               --bind '$tag_query_and_rm:execute(echo "!queryrmtag")+accept' \
                               --bind '$tag_remove:execute(echo "!rmtag")+accept' \
                               --bind '$selectall:select-all' \
                               --bind '$deselectall:deselect-all' \
                               --bind '$help:execute-silent(echo "tag" > $preview_help)+refresh-preview' \
                               --preview='papis-fzf preview' \
                               --preview-window='bottom,12%,wrap,border-none'"
   elif [[ $1 == "add" ]]; then
    # Used by add
      export FZF_DEFAULT_OPTS="--reverse -m --print-query \
                               --bind 'change:first' \
                               --bind '$add_query:execute(echo "!query")+accept' \
                               --bind '$selectall:select-all' \
                               --bind '$deselectall:deselect-all' \
                               --bind '$help:execute-silent(echo "add" > $preview_help)+refresh-preview' \
                               --preview='papis-fzf preview' \
                               --preview-window='bottom,8%,wrap,border-none'"
   elif [[ $1 == "add-nobackground" ]]; then
    # Used by add
      export FZF_DEFAULT_OPTS="--reverse -m --ansi \
                               --bind 'change:first' \
                               --bind '$selectall:select-all' \
                               --bind '$deselectall:deselect-all' \
                               --preview='echo {}' \
                               --preview-window='bottom,30%,wrap'"
   elif [[ $1 == "subselection" ]]; then
    # Used by show
      export FZF_DEFAULT_OPTS="--reverse -m --ansi --no-clear \
                               --bind 'change:first' \
                               --bind '$selectall:select-all' \
                               --bind '$deselectall:deselect-all' \
                               --preview='papis-fzf preview {}' \
                               --preview-window='bottom,30%,wrap'"
   elif [[ $1 == "cite" ]]; then
    # Used by cite
      export FZF_DEFAULT_OPTS="--reverse +m --ansi --no-clear \
                               --bind 'change:first' \
                               --bind '$cite_edit:execute(echo "edit")+abort' \
                               --bind '$help:execute-silent(echo "cite" > $preview_help)+refresh-preview' \
                               --preview='papis-fzf preview cite {}' \
                               --preview-window='bottom,7%,wrap,border-none'"

   elif [[ $1 == "xport" ]]; then
    # Used by xport
      export FZF_DEFAULT_OPTS="--reverse +m --no-clear \
                               --bind 'change:first'"
   elif [[ $1 == "citations" ]]; then
    # Used by citations
      export FZF_DEFAULT_OPTS="--reverse -m --ansi --no-clear \
                               --bind 'change:first' \
                               --bind '$citations_show:execute(echo ":show")+accept' \
                               --bind '$citations_browse:execute(echo ":browse")+accept' \
                               --bind '$citations_cite:execute(echo ":cite")+accept' \
                               --bind '$selectall:select-all' \
                               --bind '$deselectall:deselect-all' \
                               --bind '$main_yank:execute-silent($yankscript {})' \
                               --bind '$help:execute-silent(echo "citations" > $preview_help)+refresh-preview' \
                               --preview='papis-fzf preview citations {}' \
                               --preview-window='bottom,30%,wrap'"

   else
      export FZF_DEFAULT_OPTS="--reverse -m --ansi --no-clear"
   fi
}
